[package]
name = "jex-sc-raffle-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.jex-sc-raffle]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.42.0"
