// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           19
// Async Callback (empty):               1
// Total number of exported functions:  21

#![no_std]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    jex_sc_raffle
    (
        prepareRaffle
        configureTicketPrice
        startRaffle
        pickWinners
        clearEntries
        endRaffle
        buyTickets
        getRaffleStatus
        getEntries
        getBurnRatePercent
        getFeesRatePercent
        getFeesAddress
        getPrizePoolPercent
        getRaffleName
        getState
        getTicketPrice
        getTicketSaleEndTimestamp
        getTicketTokens
        getWinners
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
