// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    jex_sc_raffle
    (
        startRaffle
        pickWinners
        endRaffle
        buyTickets
        getBurnRatePercent
        getFeesAddress
        getPrize
        getState
        getTicketPrice
        getTicketSaleEndTimestamp
        getTicketToken
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
